name: Deploy React APP
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
      # run: echo
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm i
      - name: Test application
        run: npm run test
      - name: Lint application
        run: npm run lint
      - name: Build application
        run: npm run build
      - name: Deploy
        run: echo Deploying
